# Generated by Django 3.2.5 on 2021-12-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_delete_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='accepted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
