# Generated by Django 3.2.5 on 2021-12-07 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_rooms'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rooms',
            new_name='Room',
        ),
    ]
