# Generated by Django 3.2.5 on 2021-12-07 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_rooms_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendlist',
            name='room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.room'),
        ),
    ]
