# Generated by Django 3.2.5 on 2021-07-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210716_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendlist',
            name='has_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
