# Generated by Django 3.2.5 on 2021-07-28 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210728_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendlist',
            name='had_been_blocked',
        ),
    ]
