# Generated by Django 3.2.5 on 2021-09-01 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_friendlist_had_been_blocked'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
