name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Heroku CLI
      run: curl https://cli-assets.heroku.com/install.sh | sh

    - name: Set up Heroku remote with authentication
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        git remote add heroku https://heroku:${HEROKU_API_KEY}@git.heroku.com/mychat-django.git

    - name: Pull from Heroku before pushing
      run: git pull heroku main --rebase

    - name: Deploy to Heroku
      run: git push heroku main
